"""initial schema

Revision ID: 0b63504fb2a0
Revises: 
Create Date: 2026-04-11 00:53:41.993168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0b63504fb2a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('center_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_fr', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('convocation_template', sa.Text(), nullable=False),
    sa.Column('supervisors_per_room', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=9), nullable=False),
    sa.Column('name_fr', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('level', sa.Enum('BAC1', 'BAC2_NORMALE', 'BAC2_RATTRAPAGE', name='levelenum'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('supervisor_arrival_delay', sa.Integer(), nullable=False),
    sa.Column('student_arrival_delay', sa.Integer(), nullable=False),
    sa.Column('supervisors_per_room', sa.Integer(), nullable=False),
    sa.Column('max_reserves', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'VALIDATED', name='examstatusenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_fr', sa.String(length=100), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workload_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cin', sa.String(length=20), nullable=False),
    sa.Column('year', sa.String(length=9), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('bac1_count', sa.Integer(), nullable=False),
    sa.Column('bac2_count', sa.Integer(), nullable=False),
    sa.Column('morning_count', sa.Integer(), nullable=False),
    sa.Column('afternoon_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cin', 'year', name='uq_ledger_cin_year')
    )
    op.create_table('niveaux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('name_fr', sa.String(length=100), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=False),
    sa.Column('candidate_type', sa.Enum('OFFICIEL', 'LIBRE', name='candidatetypeenum'), nullable=False),
    sa.Column('room_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('name_fr', sa.String(length=100), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', name='genderenum'), nullable=False),
    sa.Column('cin', sa.String(length=20), nullable=False),
    sa.Column('som', sa.String(length=50), nullable=False),
    sa.Column('school', sa.String(length=150), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'cin', name='uq_teacher_cin_per_exam')
    )
    op.create_table('duo_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('teacher_a_id', sa.Integer(), nullable=False),
    sa.Column('teacher_b_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['teacher_a_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['teacher_b_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('niveau_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('shift', sa.Enum('MORNING', 'AFTERNOON', name='shiftenum'), nullable=False),
    sa.Column('slot_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reserve_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['niveau_id'], ['niveaux.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'niveau_id', 'day', 'shift', 'slot_order', name='uq_slot')
    )
    op.create_table('niveau_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niveau_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['niveau_id'], ['niveaux.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_exemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('exemption_type', sa.Enum('SLOT', 'SHIFT', 'DAY', name='exemptiontypeenum'), nullable=False),
    sa.Column('ref_value', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('madaoume_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_slot_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_slot_id'], ['exam_slots.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserve_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_slot_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_slot_id'], ['exam_slots.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_slot_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_slot_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('supervisors_override', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_slot_id'], ['exam_slots.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_slot_assignment_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_1_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_2_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AUTO', 'OVERRIDDEN', name='assignmentstatusenum'), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['room_slot_assignment_id'], ['room_slot_assignments.id'], ),
    sa.ForeignKeyConstraint(['supervisor_1_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['supervisor_2_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_assignments')
    op.drop_table('room_slot_assignments')
    op.drop_table('reserve_assignments')
    op.drop_table('madaoume_assignments')
    op.drop_table('teacher_exemptions')
    op.drop_table('niveau_subjects')
    op.drop_table('exam_slots')
    op.drop_table('duo_history')
    op.drop_table('teachers')
    op.drop_table('niveaux')
    op.drop_table('workload_ledger')
    op.drop_table('subjects')
    op.drop_table('rooms')
    op.drop_table('exams')
    op.drop_table('center_settings')
    # ### end Alembic commands ###
