"""add_madaoume_reserve_counts

Revision ID: 0f3336f5869e
Revises: d1e3f5a7b2c4
Create Date: 2026-05-18 17:50:09.877587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0f3336f5869e'
down_revision: Union[str, None] = 'd1e3f5a7b2c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add with a server default so existing rows get a value
    op.add_column('workload_ledger',
        sa.Column('madaoume_count', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column('workload_ledger',
        sa.Column('reserve_count', sa.Integer(), nullable=False, server_default='0')
    )

    # Remove the server default after backfill to let SQLAlchemy models handle defaults
    op.alter_column('workload_ledger', 'madaoume_count', server_default=None)
    op.alter_column('workload_ledger', 'reserve_count', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workload_ledger', 'reserve_count')
    op.drop_column('workload_ledger', 'madaoume_count')
    op.add_column('center_settings', sa.Column('morning_s2_time', sa.VARCHAR(length=20), server_default=sa.text("'10:30-12:30'::character varying"), autoincrement=False, nullable=False))
    op.add_column('center_settings', sa.Column('morning_s1_time', sa.VARCHAR(length=20), server_default=sa.text("'08:00-10:00'::character varying"), autoincrement=False, nullable=False))
    op.add_column('center_settings', sa.Column('afternoon_s1_time', sa.VARCHAR(length=20), server_default=sa.text("'14:00-16:00'::character varying"), autoincrement=False, nullable=False))
    op.add_column('center_settings', sa.Column('afternoon_s2_time', sa.VARCHAR(length=20), server_default=sa.text("'16:30-18:30'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
