"""add_exam_filiere_rooms

Revision ID: 1da3f61ae0f6
Revises: a1b2c3d4e5f6
Create Date: 2026-04-13 17:46:43.279341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1da3f61ae0f6'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_filiere_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_filiere_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('supervisors_override', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_filiere_id'], ['exam_filieres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_filiere_id', 'room_id', name='uq_efr_filiere_room')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_filiere_rooms')
    # ### end Alembic commands ###
